
== Methods

A method is a block of code designed to perform a particular task. A method encloses a set of statements and is a fundamental modular unit of Java. They let you reuse code, and provide a way for you to organize your programs, keeping them easier to understand and easier to modify. It's often said that the craft of programming is the creation of a set of methods and data structures which implement a solution to some problem or set of requirements.
 
methods are objects, like many things in Java. They can be stored in variables, other objects, or even collected into arrays. methods are very powerful because in Java, they can be passed as arguments to other methods, returned from methods, and can even have methods attached to them. The most important thing that methods can do is get *invoked*.

You create methods easily.

=== method Literal

Two examples of how you write a method literal:

[source]
----
public static int add(int parameter1, int parameter2) {
    return parameter1 + parameter2; 
}
----

[source]
----
public static int add(int p1, int p2) {
    return p1 + p2;
}
----

In both of these cases, you end up with a method named 'add' that takes two parameters and adds them, returning the result. (Yes, you could just write (p1 + p2) and everyone would understand. It's just a very simple example.) Here is another example:

=== Creating a method

[source]
----
public static void greetUser(String username) {
    System.out.println( "Hello " + username);
}

//calling/Invoking the method
greetUser("Mike Jones"); // "Hello Mike Jones"
----

=== Invoking methods

methods are meant to be _invoked_. So you can have one method call another method which calls a third method and so on; it's very common.

Imagine we have a program that gets an airplane ready for flight. We can imagine a whole series of methods we'd have to write. Things like 'loadPassengers', 'loadBaggage', 'loadFuel', 'checkTirePressures', and so on. Then we might have a 'higher level' methods which brings all these pieces together:

[source]
----
public static void prepFlight(Airplane airplane) {
    loadBaggage(airplane);
    loadPassengers(airplane);

    loadFuel(airplane);
    performPreflightChecklist(airplane.copilot);
    askTowerToDepart(airplane.pilot);
    departGate(airplane);

    taxiToRunway(airplane, mainRunway90);
    takeoff(airplane.pilot, airplane);
}
----

You can see how methods let you perform different things in a particular order, and while you might have no idea _how_ 'loadBaggage' does what it does, you can see how the program preps the airplane object for flight and makes sure everything important is done. Each of the methods from 'loadBaggage' to 'takeoff' is invoked and returns so the next one can be invoked. This is the power of methods - the ability to take some code and put it a method so that it much easier to understand.

=== Anonymous methods

A common pattern used in Java revolves around an *anonymous* method. It's a method without a name, and one that probably only gets called _once_. Something like:

[source]
----
// Anonymous methods are not typically used in Java like this
// Here's a simple method example instead:
public static void exampleMethod() {
    int x = 5;
    int y = 4;
    while (x < 100) {
        x = x + y;
    }
    System.out.println("x is " + x);
}
----

Look at that last line. What's going on here? Well, first we are creating a method object _without a name_ (so it's _anonymous_). Then on the last line, we are _invoking_ the method once (see those two parentheses? '()'?), so all the code inside gets run. (x get printed out).

You see this often in Java. It's a way to put some code into an argument to another method call.

[source]
----
int milliSecInASecond = 1000;

// Note: setTimeout doesn't exist in standard Java
// This is more like JavaScript syntax
// In Java, you would use Timer or ScheduledExecutorService
System.out.println("We waited for 5 seconds, to print this");
----

See how we pass an anonymous method to 'setTimeout' as one argument, and a timer value as the second argument? The idea here is that the anonymous method gets called at 5 seconds in the future. (Like scheduling an alarm to do something in 5 seconds).

=== method Return

Once Java reaches a return statement, the method will stop executing. methods often compute a return value. The return value is "returned" back to the "caller". You can have many returns in a methods, depending on how the flow of control is changed.

[source]
----
public static String greetUser(String username) {
    return "Hello " + username;
}

String result = greetUser("Welcome back, Mike Jones");

System.out.println(result); // will print "Hello Welcome back, Mike Jones" 
----

Or like this:

[source]
----
public static String determineWinner(Team home, Team visitor) {
    if (home.score > visitor.score) {
        return "Home Team Wins! Let's have a Parade!";
    } else if (home.score < visitor.score) {
        return "Visitors Win! (oh Well)";
    }
    return "It's a Tie!";
}
----

Notice how in this case, we check to see the scoring results with two conditions (which are, what? yes, _boolean expressions_). If neither condition is true, the third one must be the case. But if either condition is true, then we return right away, and the method is done.

Again, to be clear, we might use this method like this:

[source]
----

Team home = new Team();
home.name = "Fightin Cats";
home.score = 0;

Team visitor = new Team();
visitor.name = "Wild Horses";
visitor.score = 0;

playGame(home, visitor); // a lot of work done in this method(!)

// game is done
String result = determineWinner(home, visitor);

// and then print the result..
System.out.println(result);
----

=== method Parameters

methods can also take parameters to be used within a method. 

[source]
----
public static int addThreeNumbers(int a, int b, int c) {
    return (a + b + c);
}

public static String determineWinner(Team home, Team visitor) {
    if (home.score > visitor.score) {
        return "Home Team Wins! Let's have a Parade!";
    } else if (home.score < visitor.score) {
        return "Visitors Win! (oh Well)";
    }
    return "It's a Tie!";
}

public static int makeNegative(int number) {
    if (number > 0) {
        return -(number);
    }
    // already negative, it's less than 0
    return number;
}
----

Remember how we had the expression to see if a number was even? ( x % 2 == 0)
Now, here's a way to decide is number was divisible cleanly by another, it's a standard arithmetic expression:

[source]
----
(number % divisor == 0)
----

So to see if a number is even, we could use '(number % 2 == 0)':

[source]
----
System.out.println((8 % 2 == 0)); // true
System.out.println((7 % 2 == 0)); // false
System.out.println((4 % 2 == 0)); // true
----
And we can use the same technique to see if a number is evenly divisible by 3 or 5.

Try to write a method that will perform the following requirements:

**Exercise: Create a ZipCoder Method**

* Create a method called zipCoder
* Your method takes one parameter of type number
* Your method checks and does the following
* If parameter is divisible by 3 and 5 (15). Print ZipCoder
* If parameter is divisible by 3. Print Zip
* If parameter is divisible by 5. Print Coder
Phew...Finally
* Call the method and pass in 45 as your parameter

OKAY! Write it yourself!

Do it.

Just write it yourself.

C'mon, write your own version first.

No, really.

Wait.

Do you want to be a ZipCoder, or just a Copy-Paste Stylist?

Well, here's one solution:

[source]
----
// method ZipCoder

public static void zipCoder(int aNumber) {
    if (aNumber % 15 == 0) System.out.println("ZipCoder");
    else if (aNumber % 3 == 0) System.out.println("Zip");
    else if (aNumber % 5 == 0) System.out.println("Coder");
}

zipCoder(45); // -> ZipCoder
----

