
== Objects

Java is a language which encourages the idea of Object Oriented Programming. 
**Objects** are a fundamental idea in Java. In a Java program, a programmer will break down the problem into smaller pieces, each piece might be a small grouping of objects.

Let's think about our reliable furnace, the one that keeps us warm all winter long.
Attached to the furnace is a _thermostat_, a very simple computer.
There is a 3-way switch on most of them, one that allows you to select _off_, _heat_ or _cool_.
In the winter, of course, if you're in the northern hemisphere, you tend to choose _heat_.

If the thermostat is rather old fashion, it might have a ring you rotate to set the temperature, say 68 degrees.

A Java programmer writes code which in _classes_ and then, when a java program runs, _objects_ are created 
All but one of them are called “primitive” data types, because their values contain only a single thing (be it a string or a number or whatever).

In contrast, *objects* are used to store *keyed* collections of various data and more complex entities. 
_Objects_ add tremendous power to Java and penetrate almost every aspect of the language. 
Here are a few different objects, all these are actually objects in Java, which makes the language rather elegant:

* arrays
* functions
* regular expressions 
* objects 

Objects are used to collect and organize data - and that data can be variable values, functions and other things. 
Objects can also contain other objects(!), in kind of a "nesting" way. 
This allows for large data structures to be built using a very simple and elegant mechanism.


[source]
----
// Creating a Person object using a class
class Person {
    String firstname;
    String lastname;
    int homedistrict;
    String[] skills;
    
    public Person(String firstname, String lastname, int homedistrict, String[] skills) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.homedistrict = homedistrict;
        this.skills = skills;
    }
}

Person katniss = new Person("Katniss", "Everdene", 12, 
    new String[]{"foraging", "wildlife", "hunting", "survival"});
----

Notice how you use commas for all but the last one in the list?

=== Object Creation

We can imagine an object as a container which has copies of *instance variables* (or field) that can be different for each different
object of the same class.
Fields can be any Java data type at all. 
Let's create a sample player object for a game:

[source]
----
// Creating a Player class with nested Weapons class
class Weapon {
    String sword;
    String bow;
    int arrows;
    
    public Weapon(String sword, String bow, int arrows) {
        this.sword = sword;
        this.bow = bow;
        this.arrows = arrows;
    }
}

class Player {
    String name;
    String species;
    String superPower;
    int lives;
    Weapon weapon;
    
    public Player(String name, String species, String superPower, int lives, Weapon weapons) {
        this.name = name;
        this.species = species;
        this.superPower = superPower;
        this.lives = lives;
        this.weapons = weapons;
    }
}

Player player1 = new Player("Rocco", "warrior", "flight", 4, 
    new Weapon("Excalibur", "Yew", 12));
----

This 'player1' object has 5 instance variables. 
One of those instance variables is a nested object, the 'weapons' field has another object with 3 instance variable inside of the weapon object. 

=== Field Retrieval

In Java, you typically use **getter** and **setter** methods to access and modify instance variables 
(fields) of a class. 
This approach follows the principle of **encapsulation**, which helps protect the internal state of an object.

### Example

Suppose you have a `Player` class with a `name` field:

````java
public class Player {
    private String name; // instance variable

    // Getter method
    public String getName() {
        return name;
    }

    // Setter method
    public void setName(String newName) {
        name = newName;
    }
}
````

- **Getter** (`getName()`): Returns the value of `name`.
- **Setter** (`setName(String newName)`): Updates the value of `name`.

### Usage

````java
Player player1 = new Player();
player1.setName("Rocco");              // Set the name using the setter
System.out.println(player1.getName()); // Get the name using the getter
````

**Gotcha:**  
Directly accessing fields (e.g., `player1.name = "Rocco";`) is only possible if the field is `public`. 
Using getters and setters is safer and more flexible, especially if you want to add validation or logic later.

=== Object Reference

This next little bit will stretch your mind a bit. 

If we have an object:

[source]
----
class Airplane {
    String type;
    double topSpeed;
    int passengerLimit;
    int passengersOnboard;
    String destination;
    String origin;
    
    public Airplane(String type, double topSpeed, int passengerLimit, int passengersOnboard) {
        this.type = type;
        this.topSpeed = topSpeed;
        this.passengerLimit = passengerLimit;
        this.passengersOnboard = passengersOnboard;
    }

    // assume we have all the setters and getters we need.
}

Airplane airplane512 = new Airplane("airbusA330", 0.86, 253, 0);
----

We have built a plane object.

[source]
----
Airplane flight77 = airplane512;  // I'm assigning a plane to a flight
flight77.setDestination("Tokyo");
flight77.setOrigin("Seattle");

// now watch carefully...
flight77.setPassengersOnboard(120);

// and if I print out some of the properties...
System.out.println(airplane512.passengersOnboard);  // 120
System.out.println(flight77.type); // airbusA330
System.out.println(airplane512.type); // airbusA330
----

This is because both flight77 and airplane512 _refer to the *same* object. 
so when you make changes through the flight77 name, the properties in the object change, and 
you can get and/or set properties through the airplane512 name as well. 
This proves very powerful in many cases.

=== Instance Methods

Now to make things even more powerful, Java objects can have _methods_ attached to them.
Let's build a special counter object, something we might use in a program or app somewhere.

As you may be aware, in American football there are four common changes to a team's score during a game:

[source]
----
import java.util.HashMap;
import java.util.Map;

class ScoreCounter {
    private Map<String, Integer> options;
    private int score;
    
    public ScoreCounter() {
        options = new HashMap<>();
        options.put("fieldgoal", 3);
        options.put("touchdown", 6);
        options.put("point_after_touchdown", 1);
        options.put("safety", 2);
        score = 0;
    }
    
    public void touchdown() {
        this.score += this.options.get("touchdown");
    }
    
    public void fieldgoal() {
        this.score += this.options.get("fieldgoal");
    }
    
    public void pat() {
        this.score += this.options.get("point_after_touchdown");
    }
    
    public void safety() {
        this.score += this.options.get("safety");
    }
    
    public int getScore() {
        return this.score;
    }
}

// Example usage:
public class Main {
    public static void main(String[] args) {
        ScoreCounter scoreCounter = new ScoreCounter();
        // You can now use scoreCounter here
    }
}
----

We can use that object, with its methods like this:

[source]
----
scoreCounter.touchdown(); // add 6
scoreCounter.pat(); // add 1
scoreCounter.fieldgoal(); // add 3

System.out.println(scoreCounter.getScore()); // ??
----

There are two data properties (options and score), and 5(!) functions. 
These functions are called *methods* (functions which are attached to an object), 
and get invoked when you make the _method call_ (or _invoke_ the method on the _object_).

Notice the *this* variable. _This_ is the special variable used to refer to the _object itself_. 
(which is a rather advanced topic for this book, so, we'll leave it right there. 
When you get a chance, read about _this_ in a deeper Java resource.)

=== Follow Ons

We have tried to give you some of the very basic parts of OOP in Java, 
for you to get a very basic understanding of coding in Java.

There are a number of very powerful things we have left out of this discussion about Java objects.

We also have not discussed an extremely powerful concept, *closures*. 
But rest assured, there is much much more for you to learn about Objects in Java. 

Master what we've written about here and then forge ahead into more complicated and powerful capabilities.

There is a lot more to learn about Java.
But you made it this far, so perhaps you have what it takes to learn the 21st century super-power of coding.
__(I do hope so.)__
