
=== Variables

In Java, variables are containers used to store data while the program is running. 
Variables can be named just about anything, and often are named things that make you think about what you store there.

Think of them as little boxes you can put data into, to keep it there and not lose it.
If you wanted to track a number, an age of someone, you can create a variable to keep it in.

[source]
----
int age = 3;
----

Now, if we wanted to indicate that someone had a birthday, we might add 1 to the variable.

[source]
----
int age = age + 1;
----

At this point, the _age_ variable as 4 in it.



There are some rules about variable names. 

- All Variables must be named.
- Names can contain letters, digits, underscores, and dollar signs
- Names must begin with a letter
- Names can also begin with $ and _ but are often used in special cases
- Names are case sensitive (y and Y are different variables)
- Reserved words (like Java keywords) cannot be used as names
- All variable names must be unique (no two alike)

So this means the following are fine for variable names in Java:

[source]
----
x
area
height
width
currentScore
playerOne
playerTwo
$sumOfCredits
_lastPlay
isPlayerAlive
----

And uppercase and lowercase letters are different.
So each of these are DIFFERENT variables even 
though they are based on the same word(s).

[source]
----
currentSpeed
current_speed
currentspeed
CURRENT_SPEED
----

So be careful with UPPERCASE and lowercase letters in variable names.

==== Declaring a Variable

[source]
----
int x;
----
This creates a variable *x* that can hold an integer (int) primitive type. But it has NO value assigned to it, so if we...

[source]
----
System.out.println(x);  // -> undefined, although it will probably print zero.
----

If we were to declare a variable named 'cats' and assign it the value 3 (because we have 3 cats?):

[source]
----
int cats = 3;
System.out.println(cats);  // -> 3
----

==== Assign a value to a variable

[source]
----
int age = 19; 
String name = "James";
System.out.println(name, "is", age, "years old"); // -> James is 19 years old
age = 21;
name = "Gina";
System.out.println(name, "is", age, "years old"); // -> Gina is 21 years old
----

_NOTICE_ how the **first time** we use _age_ and _name_ we must _declare_ those variables.
But the _second time_ (and any use thereafter) we don't have to put _int_ or _String_ in front of the name.

This is how we make sure we don't use variables we have not declared (which in Java is a _syntax_ error).

==== Reassigning a value to a variable

[source]
----
String x = "five";
System.out.println(x); // -> five
x = "nineteen";
System.out.println(x); // -> nineteen
----

Notice how we don't use "String" again, when we assign "nineteen" to x. 
We can assign a variable as many times as we might need to.

[source]
----
int age = 3;
// have a birthday
age = age + 1;
// have another birthday
age = age + 1;
System.out.println(age); // -> 5
----

Notice here how age's current value is used, added one to it, and re-assigned _back into the variable *age*_.

Java, once you declare a variable as an _int_

[source]
----
int height = 62.0; // inches maybe?
System.out.println(height); // -> 62

height = "very tall"; // Java WILL NOT LET you do this.
System.out.println(height);

----

_Java demands that once you tell it height is a int, you cannot change it to a String._
You might think, but hey, _I'm the programmer_, but in fact, Java is protecting you from a common
logic error.
And in doing so, is shows what we mean by Java being a **strongly-typed language**.
Once you declare something to be of a given type, you cannot change the type while the program is running.

=== Constants

Constants are like let variables but they contain values that do NOT change such as a person’s date of birth. Convention is to capitalize constant variable names. 

You make a double or int or String a constant by marking it **final**.

[source]
----
final String DATE_OF_BIRTH = "04-02-2005";
DATE_OF_BIRTH = "04-10-2005"; // <-error

final double SPEED_OF_LIGHT = 670_616_629.0; // miles per hour

SPEED_OF_LIGHT = 700_000_000.0; // ERROR, cannot changed things marked final
----

An attempt to re-assign a value to a constant (something marked with _final_) will fail.


=== Data Types

Java can keep track of a number of different kinds of data, and these are known
as "primitive data types". There are 5 of them.

* *Number* - there are two kinds of numbers: integers and floating point
** *Integers* (or **int**) are like 0, -4, 5, 6, 1234
** *Floating Point* (or **double**) are numbers where the decimals matter like  0.005, 1.7, 3.14159, -1600300.4329
* *String* - an array of characters - 
** like 'text' or "Hello, World!"
* *Boolean* - is either *true* or *false*
** often used to decide things like isPlayer(1).alive() [true or false?]


It is common for a computer language to want to know if data is a bunch numbers or text. Tracking
what **type** a piece of data is is very important. And it is the programmer's job to make sure all the 
data get handled in the right ways. 

So Java has a few fundamental *data types* that it can handle. And we will cover each one in turn. 

[TIP]
====
Create variables for each primitive data type:

- double
- int
- string 
- boolean

Store a value in each.

====

[source]
----
// Here are some samples. 

// integer
int x = 0;

// boolean
boolean playerOneAlive = true;

// float
double currentSpeed = 55.0;

// string
String playerOneName = "Rocco";

// constant integer

final int maxPainScore = 150000;
----

Now, you try it. Write down a variable name and assign
a normal value to it.

[source]
----
// Here are some samples. 

// integer
int applesPerBushel =     ;

// boolean
boolean isEngineRunning =          ;

// float
double myGradePointAverage =       ;

// string
String myDogName =         ;

// constant integer

final int floorsInMyBuilding =         ;
----

