
== Algebraic Equations

Some of the most fundamental of computer programs have been ones that
take the drudgery of doing math by a person, and making the computer do the math.
These kinds of _computations_ rely on the fact that the computer won't do the wrong thing if it's programed carefully.

Given a simple math equation like:
[TIP]
====
a = b3 - 6 and if b equals 3, then a equals ?
====

In math class, your teacher would have said "How do we solve for a?" The best way to solve for `a = b3 - 6`
is to

- figure out what b times 3 is (well, if b equals 3, then 3 times 3 is 9)
- subtract 6 from b times 3 (and then 9 minus 6 is 3)

[source, Java]
----
// And in Java:
// a = b3 - 6 

int b = 3;
int a = b * 3 - 6;
System.out.println(a); // -> 3
----

Now you try it. 

[TIP]
====
Solve the equation with Java...

q = 2j + 20

if j = 5, then q = ?

Take a moment and write down your solution before reading on.
====

[source, Java]
----
int q = 0; 
int j = 5;
q = 2 * j + 20;
System.out.println(q); // -> 30
----

Let's try another...

[TIP]
====
Solve the equation with Java...

x = 5y + y^3^ - 7

if y=2, x = ?

and print out x.
====


My solution is pretty simple.
[source, Java]
----
int y = 2; 
int x = 5 * y + Math.pow(y, 3) - 7;
System.out.println(x); // -> 11
----

=== _Trigonometry_

The word trigonometry comes from the Greek words, trigonon ("triangle") + metron ("measure"). 
We use trigonometry to find angles, distances and areas.

For example, if we wanted to find the area of a triangular piece of land, we could use the
equation *AreaOfaTriangle = height * base / 2*

Therefore we just need to create variables for each and use the operators to calculate the area.

[TIP]
====
Calculate Area of a Triangle in Java
Height is 20
Base is 10
Formula: A = h * b / 2
====

[source, Java]
----
int height = 20;
int base = 10;	
int areaOfaTriangle  =  height * base / 2;
System.out.println(areaOfaTriangle); // -> 100
----


[TIP]
====
Calculate the area of a circle whose radius is 7.7
Formula: area = Pi * radius^2^
====
Hint: You'll need to use a constant Math property!


[source, Java]
----
int radius = 7.7;	
int area  =  Math.PI * Math.pow(radius, 2);
System.out.println(area); // -> 186.26502843133886 (wow)
----


