
Arrays are a very powerful idea in many programming languages. Let's start with *why* we need them.

Imagine you have a small number of things you want to track. Let's use our vague computer game we've been using for an example. The game has 5 players, friends that get together over the internet to play a dungeon game.

Now, if you're the coder of this game you could keep track of each player's healthScore by have 5 different variables. (for players Zero to Four)

[source]
----
int playerZeroHealthScore = 100;
int playerOneHealthScore = 100;
int playerTwoHealthScore = 100;
int playerThreeHealthScore = 100;
int playerFourHealthScore = 100;
----

If we setup these 5 variables, our game can track 5 players! But *we'd have to change the game's code to track SIX players.* Well, that's not good. Kind of silly actually. 

To get around this kind of problem we use an *array*. We could ask, "how many players are playing?", and then make an array that size. We know we need to track each player's healthScore, so we create an array:

[source]
----
int[] playerHealthScores = new int[]{100, 100, 100, 100, 100};
----

Now, like a _string_, array indexes start at zero.

[source]
----
                                 //   0    1    2    3    4
int[] playerHealthScores = new int[]{100, 100, 100, 100, 100};
----

This array is a *data structure* - a way for us to keep track of lots of data in a controlled fashion. (We can make arrays any size we'd like.)
If we need to deduct health points from one of the players, we can do something like this:

[source]
----
int majorHit = 50;

playerHealthScores[2] = 67;  // player 2 just took a hit!

playerHealthScores[1] = 105;  // player one is getting stronger.

playerHealthScores[3] = playerHealthScores[3] - majorHit;
----

The best way to think about arrays is like all those postal boxes at the post office. Each box has a number on it, and things get put in the box depending on the box number.

Arrays are *indexed* like that. Each array slot has an index number, starting at zero. See how we use the number 2 to _index_ into the playerHealthScore array?

Arrays:

* Can store multiple values in a single variable
* Start counting from index position zero
* Elements can be primitive data types or/and Objects

So let's think about an array of donuts for the following examples.

=== Declaring Arrays

Declaring and initializing some arrays in Java:

[source]
----
String[] donuts = new String[]{"chocolate", "glazed", "jelly"};
----

=== Accessing elements of an Array

We use square brackets to get elements by their index. We'll use an array of
strings to identify our donuts. Sometimes, we say something like "donuts sub 2" to mean _donuts[2]_.

[source]
----
String[] donuts = new String[]{"chocolate", "glazed", "jelly"};

System.out.println(donuts[0]);  // "chocolate" (we could say "donuts sub zero")

System.out.println(donuts[2]);  // "jelly"
----

=== Get the size of an Array

We can use the *length* property to find the size of an array.

[source]
----
String[] donuts = new String[]{"chocolate", "glazed", "jelly"};

System.out.println(donuts.length);  // it'll print 3
----

Note: A string is kind of like ARRAY of single characters.


=== Get the last element of an Array

If we use the _length_ property carefully, we can always get the last element in an array.

[source]
----
String[] donuts = new String[]{"chocolate", "glazed", "jelly", "strawberry"};

System.out.println(donuts[donuts.length - 1]); // strawberry
----


=== Change an element of an Array

We can change the value within an array to anything we'd like, as long as it is the same *type* as the array started with.

[source]
----
System.out.println(donuts[2]); // jelly

                          // .    0            1         2           3
donuts[2] = "powdered";   // -> ["chocolate", "glazed", "powdered", "strawberry"]

System.out.println(donuts[2]); // powdered
----

