
Let's start with a really simple program.
Perhaps the simplest Java program is:

[source]
----
public class Main {
  public static void main(String[] args) {
    System.out.println("Hello, World!");
  }
}
----

This program just prints "Hello, World!".

_System.out.println_, in this case, means _outputting_ or _printing_ the "Hello, World!" somewhere. That somewhere is probably the terminal where the program was run.


We will use `System.out.println` to do a lot in the coming pages. It's a simple statement, one that in other languages might be `print` or `write` or `puts` (and why we all cannot just agree on one way to do this, well, beats me. Java's is `System.out.println`)

Here's your second Java program: 

[source]
----
public class Main {
  public static void main(String[] args) {
    double milesPerHour = 55.0;
    System.out.println("Car's Speed: " + milesPerHour);
  }
}
----

Now, how do we `run` this program? Use a REPLI.it!!

****
> sh -c javac -classpath .:target/dependency/* -d . $(find . -type f -name '*.java')
> java -classpath .:target/dependency/* Main
Car's Speed: 55.0
>  
****

Cool, huh? The ability to communicate with you is one of Java's most fundamental capabilities. And you've run two Java programs. Congratulations, you're a coder. (Well, at least for today you are.)

== Comments

While you're not thinking about the long term, or about large Java programs, there is a powerful thing in Java that helps with tracking comments and notes about the code.

In your program, you can write stuff that Java will ignore, it's just there for you (or readers of your code). We use two slashes to start a comment, and the comment goes to the end of the line.
Java will ignore anything on a line after two forward slashes. "//"

[source]
----
// this is a comment. it might describe something in the code.
int x = 53 - 11;

int y = x * 4; // this is also a comment.
----

Often, you'll see something like this in this book.

[source]
----
public class Main {
  public static void main(String[] args) {
    double flourAmount = 3.5;
    System.out.println(flourAmount); // -> 3.5
  }
}
----

That comment at the end of the console.log line is showing what you can expect to see in the output. Here it would be "3.5" printed by itself. Try it in your bookmarked Repl.

We can also add useful stuff to the .log call. 

[source]
----
public class Main {
  public static void main(String[] args) {
    double flourAmount = 3.5;
    System.out.println("We need " + flourAmount + " cups of flour."); // -> 3.5
  }
}
----

See how Java types it all out as a useful phrase? That proves to be very handy in a million-plus (or more) cases.

Comments can be used to explain tricky bits of code, or describe what you should see in output. Comments are your friend. 

== BUT WAIT!!!

What does `int` and `double` signify? Well, see how they proceed another word?

[source]
----
public class Main {
  public static void main(String[] args) {
    double flourAmount = 3.5;
//  ^^^^^^ ^^^^^^^^^^^  
    System.out.println("We need " + flourAmount + " cups of flour."); // -> 3.5
  }
}
----

It is our way of telling Java what `flourAmount` is. We want `flourAmount` to be place holder for the number `3.5`, because makes
the code easier to read and understand. See much more on this, up ahead, in `variables`.

Oh, and `int`?? Well, it means a number, but just an integer like 0, 1, 2, 42, 99, etc. A `double` can have decimal point and some number after, so I can write `3.5` or `42.0`.

== Statements and Expressions

In Java, there are parts of a program and different parts have different names. Two of the most basic (and fundamental) are *statements* and *expressions*.

=== Expressions

An *expression* is something that needs to be _computed_ to find out the answer. Here are a few simple ones.

[source]
----
2 + 2 * 65536

speed > 55.0

regularPrice * (1.0 - salePercentOff)
----

Each of these lines is something we'd like Java to *compute* for us. That computation is often referred to as "evaluation" or "evaluate the expression" to get to the answer. 
There are two kinds of expressions in Java, _arithmetic expressions_ and _boolean expressions_.

*Arithmetic expressions* are, as their name implies, something that require arithmetic to get the answer. An expression like "5 + 8 - 3" gets _evaluated_ to 10. 
So an arithmetic expression will end up being a _number_.

*Boolean expressions* result in either a True or a False value. 
Example: "maxSpeed > 500.0" - this is either true or false depending on the value of maxSpeed. 
Or "homeTeamScore > visitorTeamScore" which will be true is and only if the Home team's score is greater than
the Visitor team's score. Both _scores_ are numbers, the result of the **greater than** makes the result of the
epxression a _boolean expression_ (either **true** or **false**). 

=== Statements

A *statement* is just a line of Java. It ends with a ';' (semi-colon).

[source]
----
public class Main {
  public static void main(String[] args) {
    // at the Grocery

    double salesTaxRate = 0.06;
    double totalGroceries = 38.99;
    double salesTax = totalGroceries * salesTaxRate;
    double chargeToCard = totalGroceries + salesTax;
  }
}
----
And this is what a Java program looks like. It's just a list of statements, one after the other, that get computed from the top down.

Some of the statements have expressions in them (like totalGroceries * salesTaxRate), while some are just simple *assignment* statements (like totalGroceries = 38.99, where we assign the variable 'totalGroceries' the value 38.99). 
Don't panic. These are just some simple examples of Java to give you a feel for it. 
We'll go thru each of these kinds of things slowly in sections ahead.

=== Multi-line Statements

In this book, you may see that the code used in examples is longer than can fit on one line in the code boxes. Well, Java doesn't care. That's why it has *semi-colons* ';' at the end of the statements. So to be clear, a statement with long variable names is the same as one with a short name.

[source]
----
k = h * kph - (rest / 60);

kilometersCycled = numberOfHoursPedalled * kilometersPerHour - (totalMinutesOfRest / 60);
----

When you come across code that goes onto multiple lines, do like Java does, read until you find the ';'. It's like a period in an English sentence.

=== Block Statement

Very often in Java, we will see a *block* of statements. It is a list of statements inside of a pair of curly-braces "{ }". It acts like a container to make clear what statements are included in the block.

[source]
----
if (magePower > 120.0) {
    maxMagic = 500.0;
    lifeSpan = 800.0;
    maxWeapons = magePower / maxPowerPerWeapon;
}

// some more code
----

See those curly-braces? They start and stop the _block_, and contain the statements within. You can also see how the code is indented, but the real key are those braces. You'll see lots of blocks when you're looking at Java code.

And, it's a bad idea, but this code:

[source]
----
if (wizardStrength > 120.0) { maxMagic = Wizard.maxpower(); lifeSpan = Wizard.maxlife(); maxWeapons = wizardStrength * numberOfWands; }
----

is identical to this:

[source]
----
if (wizardStrength > 120.0) { 
    maxMagic = Wizard.maxpower();
    lifeSpan = Wizard.maxlife();
    maxWeapons = wizardStrength * numberOfWands;
}
----

But the SECOND example is formatted much cleaner, making it more readable and therefore easier to understand.


