
JavaScript can do math. And many early programming problems you will come across deal with doing fairly easy math. There are ways to do lots of useful things with numbers. 

=== Basics

[cols=",,",options="header",]
|===
|Operator |Name |Description
|+ |Addition |Add two values
|- |Subtraction |Subtract one from another
|* |Multiplication |Multiply 2 values
|/ |Division |Divide 2 numbers
|% |Modulus |Remainder after division
|++ |Increment |Increase value by 1
|- - |Decrement |Decrease value by 1
|===

Say we needed to multiply two numbers. Maybe 2 times 3. Now we could easily write a program
that printed that result.

[source, js]
----
console.log(2 * 3); 
----
And that will print 6 on the console. But maybe we'd like to make it a little more
complete.

[source, js]
----
let a = 2; 
let b = 3;
// Multiply a times b
let answer = a * b;
console.log(answer); // -> 6
----

Here we have set up two variables, a and b, for our _operands_ and a final _answer_ variable.
But, it's pretty much the same as the more simple example above.

Using this as a model, how would you write programs to solve these problems?

[TIP]
====
* Lab 1: Subtract A from B and print the result
* Lab 2: Divide A by B and print the result
* Lab 3: Use an operator to increase A by 1 and print result
* Lab 4: Find remainder of A of b
====

[source, javascript]
----
let a = 9; 
let b = 3;

let L1 = b - a;
let L2 = a / b;
let L3 = a + 1;
//or using increment
L3 = a++;
let L4 = a % b;
console.log(L1); // -> -6
console.log(L2); // -> 3
console.log(L3); // -> 10
console.log(L4); // -> 0
L4 = 10 % b;
console.log(L4); // now -> 1
----

=== Division and Remainder

We know that we can do regular division. If have a simple program like this, we know 
what to expect:

----
let a = 6 / 3; // -> 2
let a = 12 / 3; // -> 4
let a = 15 / 3; // -> 5
let a = 10 / 4; // -> 2.5
----

But sometimes, we have a need to know what the remainder of a division is.
The remainder operator %, despite its appearance, is not related to percents.

The result of a % b is the remainder of the integer division of a by b.

[source, js]
----
console.log( 5 % 2 ); // 1, a remainder of 5 divided by 2
console.log( 8 % 3 ); // 2, a remainder of 8 divided by 3
----

Now what's this about '%' (the remainder) operator?

[source, js]
----
let a = 3; 
let b = 2;
// Modulus (Remainder)
let answer = a % b;
console.log(answer); // -> 1
----

[source, js]
----
let a = 19; 
let b = 4;
// Remainder
let answer = a % b;
console.log(answer); // -> 3
----

[source, js]
----
let a = 4; 
let b = 4;
// Remainder

for (a = 4; a < 13; a++) {
    console.log(a, a % b); // would produce
}
// 4 0
// 5 1
// 6 2
// 7 3
// 8 0
// 9 1
// 10 2
// 11 3
// 12 0
----

=== Order is Important

A strange thing about these operators is the order in which they are evaluated. Let's take a look at this expression.

****
6 × 2 + 30
****

We can do this one of two ways:

* Say we like to do multiplication _(I know, who is that?)_
** we would then do the "6 times 2" part first, giving us 12.
** then we'd add the 30 to 12 giving us 42 footnote:[The answer to life, the universe and Everything.]
* But say we don't like multiplication, and want to save it for later...
** we would add 2+30 first, giving us 32
** and then we multiply it by 6, and, whoa, we get 192!

Wait! Which is right? How can the answers be so different, depending on the order we do the math in?
Well, this shows us that the Order of Operations is important. And people have decided upon
that order so that this kind of confusion goes away.

Basically, multiply and divide are higher priority than add and subtract. And exponents (powers) are highest priority of all.

There is a simple way to remember this.

==== P.E.M.D.A.S

Use this phrase to memorize the default order of operations in JavaScript.

****
Please Excuse My Dear Aunt Sally

* Parenthesis ( )
* Exponents 2^3^
* Multiplication * and Division / 
* Addition + and Subtraction - 
****

[WARNING]
====
Divide and Multiply rank equally (and go left to right)
So, if we have "6 * 3 / 2", we would multiply first and then divide.
"6 * 3 / 2" is 9

Add and Subtract rank equally (and go left to right)
So if we have "9 - 6 + 5", we subtract first and then add.
"9 - 6 + 5" is 8
====

[TIP]
====
30 + 6 × 2   How should this be solved?

Right way to solve 30 + 6 × 2 is first multiply, 6 × 2 = 12, then add 30 + 12 = 42
====

This is because the multiplication is _higher priority_ than the addition, _even though the addition is before the multiplication_ in the expression. Let's check it in JavaScript:

[source, js]
----
let result = 30 + 6 * 2;
console.log(result);
----

This gives us 42. 

Now there is another way to force JavaScript to do things "out of order" with parenthesis. 

[TIP]
====
(30 + 6) × 2

What happens now?
====

[source, js]
----
let result = (30 + 6) * 2;
console.log(result);
----

What's going to happen? Will the answer be 42 or 72?

=== JavaScript Math Object

There is a useful thing in JavaScript called the Math object which allows you to perform mathematical tasks on numbers.


* Math.PI; - returns 3.141592653589793
* Math.round(4.7);    // returns 5
* Math.round(4.4);    // returns 4
* Math.pow(x, y) - the value of x to the power of y - x^y^
* Math.pow(8, 2);      // returns 64
* Math.sqrt(x) - returns the square root of x
* Math.sqrt(64);      // returns 8

[IMPORTANT]
====
What does "returns" mean?

When we ask a 'function' like sqrt to do some work for us, we have to code something like:

[source]
----
let squareRootTwo = Math.sqrt(2.0);
console.log(squareRootTwo);
----

We will get "1.4142135623730951" in the output. That number (squareRootTwo) 
is the square root of 2, and it is 
the result of the function and _what the function sqrt "returns"'_.

====

*Math.pow() Example*

Say we need to compute "6^2^ + 5"

[source]
----
let result = Math.pow(6,2) + 5;
console.log(result);
----

What will the answer be? 279936 or 41?

How did JavaScript solve it?

Well, 6^2^ is the same as 6 * 6.
And 6 * 6 = 36,
then add 36 + 5 = 41.

You'll learn a lot more about working with numbers in your career as a coder. This is really just the very basic of beginnings.
